// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDYRIanQHfcCEIiPSD_Pr2mLHOlcXpcfs',
    appId: '1:439958613854:web:0a7b6eae9fb54525e529cf',
    messagingSenderId: '439958613854',
    projectId: 'subtracker-5ac3f',
    authDomain: 'subtracker-5ac3f.firebaseapp.com',
    storageBucket: 'subtracker-5ac3f.firebasestorage.app',
    measurementId: 'G-561DQX3TZ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGCHEBEBRP_c1uh_9KRzAEkHDnOEzWs08',
    appId: '1:439958613854:android:cfcee5c97028a878e529cf',
    messagingSenderId: '439958613854',
    projectId: 'subtracker-5ac3f',
    storageBucket: 'subtracker-5ac3f.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiwCHP6aF3oANmLSIve5c4tgtJbxWeqQY',
    appId: '1:439958613854:ios:effb358f88a5f468e529cf',
    messagingSenderId: '439958613854',
    projectId: 'subtracker-5ac3f',
    storageBucket: 'subtracker-5ac3f.firebasestorage.app',
    androidClientId: '439958613854-rikgu3ivin5tqdt3alm0ovgufsd9rtpn.apps.googleusercontent.com',
    iosClientId: '439958613854-jth7lp2ggg7r3p03ksmlaqq4q242slof.apps.googleusercontent.com',
    iosBundleId: 'com.example.subtrackiq',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiwCHP6aF3oANmLSIve5c4tgtJbxWeqQY',
    appId: '1:439958613854:ios:effb358f88a5f468e529cf',
    messagingSenderId: '439958613854',
    projectId: 'subtracker-5ac3f',
    storageBucket: 'subtracker-5ac3f.firebasestorage.app',
    androidClientId: '439958613854-rikgu3ivin5tqdt3alm0ovgufsd9rtpn.apps.googleusercontent.com',
    iosClientId: '439958613854-jth7lp2ggg7r3p03ksmlaqq4q242slof.apps.googleusercontent.com',
    iosBundleId: 'com.example.subtrackiq',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDYRIanQHfcCEIiPSD_Pr2mLHOlcXpcfs',
    appId: '1:439958613854:web:267d8ea75efb9f95e529cf',
    messagingSenderId: '439958613854',
    projectId: 'subtracker-5ac3f',
    authDomain: 'subtracker-5ac3f.firebaseapp.com',
    storageBucket: 'subtracker-5ac3f.firebasestorage.app',
    measurementId: 'G-MKZZV8WBX5',
  );
}
